apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-hello-world-es5g
  namespace: sde-rcook-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d215cf885eb662e03c686e3eaa13e643062a90e6cb43a78d394cd7706fe1b5d2
        name: container-image
        resources: {}
status: {}
