apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-hello-world-es5g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-hello-world-es5g
    app.kubernetes.io/part-of: my-app
  name: node-hello-world-es5g
  namespace: sde-rcook-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: node-hello-world-es5g
status:
  loadBalancer: {}
